// Generated by CoffeeScript 1.9.0
'use strict';
var DEV, FOLDERS, PROD, SRC_PATHS, coffee, gulp, gulpif, gutil, knownOptions, minimist, options, uglify;

gulp = require('gulp');

gulpif = require('gulp-if');

uglify = require('gulp-uglify');

coffee = require('gulp-coffee');

gutil = require('gulp-util');

DEV = 'dev';

PROD = 'prod';

FOLDERS = {
  DEV: './src/',
  PROD: './public/'
};

SRC_PATHS = {
  JS: './js/',
  COFFEE: './coffee/'
};

minimist = require('minimist');

knownOptions = {
  string: 'env',
  "default": {
    env: process.env.NODE_ENV || PROD
  }
};

options = minimist(process.argv.slice(2), knownOptions);

gulp.task('scripts', function() {
  gulp.src("" + FOLDERS.DEV + SRC_PATHS.COFFEE + "*.coffee").pipe(coffee({
    bare: true
  })).on('error', gutil.log).pipe(gulp.dest("" + FOLDERS.DEV + SRC_PATHS.JS));
  return gulp.src("" + FOLDERS.DEV + SRC_PATHS.JS + "*.js").pipe(gulpif(options.env === PROD, uglify())).pipe(gulp.dest("" + FOLDERS.PROD + SRC_PATHS.JS));
});

gulp.task('default', ['scripts']);
